### ISSUE TITLE
Enable compression

### ISSUE THREAD

**Issue by MiroCillik** [keboola/ssh-tunnel#6]
Add `-C` parameter.

**Comment by padak** [comment]
@MiroCillik zvládl bys tohle zprioritizovatm prosím? V HC by to mohlo masivně pomoct s přenosem dat. Tady je příklad 

![image](https://user-images.githubusercontent.com/1427901/49448291-dc8c9f00-f7d8-11e8-94e4-a4c2a350acf8.png)

Kde je vidět že extrakce trvala 4h40min a přitom to má pár GB.

**Comment by padak** [comment]
Note to self: https://connection.keboola.com/admin/projects/4390/jobs/467972414

**Comment by MiroCillik** [comment]
Oki, zajtra na to mrknem

**Comment by padak** [comment]
díky! klidně přes feature, ať to nemá hned každej. bylo by super to mít
jako přepínač v UI, ale obejdeme se bez toho.

--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek



út 4. 12. 2018 v 17:25 odesílatel Miroslav Čillík <notifications@github.com>
napsal:

**Comment by MiroCillik** [comment]
@padak jedna sa o Postgre Extraktor?

**Comment by padak** [comment]
@MiroCillik ano

**Comment by ErikZigo** [comment]
Miro nestihl pred dovolenou updatnout ten postgre na ssh tunel s kompresi. Ja na to zitra kuknu.

**Comment by padak** [comment]
@ErikZigo díky moc!

**Comment by MiroCillik** [comment]
Updatol som ten samotny ssh tunnel, vo writeri (alebo v db-common?) by malo
stacit pridat parameter 'compression'. A v UI v SSH sekci pridat na to
checkbox.
